### ISSUE TITLE
I get undefined when import

### ISSUE THREAD

**Issue by Menda** [avital/meteor-mocha-for-1.3#1]
Hi @avital. I have Meteor beta 11 installed in my system and tried this simple code.

    import { mocha } from 'meteor/avital:mocha';
    import { chai } from 'meteor/practicalmeteor:chai';
    import expect from 'expect';

    const isTestTopLevel = Meteor.isTest;

    function one() {
      return {
        isTestTopLevel,
        isTestRuntime: Meteor.isTest,
      };
    }

    export { one };

    describe('one', function () {
      it('knows whether we are running tests in top level imported code', () => {
        const result = one();
        expect(result.isTestTopLevel).toBe(true);
      });

      it('knows whether we are running tests it imported function', () => {
        const result = one();
        expect(result.isTestRuntime).toBe(true);
      });

      it('knows whether we are running tests in test file', () => {
        expect(Meteor.isTest).toBe(true);
      });

      it('can import from avital:mocha', () => {
        expect(mocha).toNotBe(undefined);
      });

      it('can import from practicalmeteor:chai', () => {
        expect(chai).toNotBe(undefined);
      });
    });

<img width="639" alt="screen shot 2016-02-26 at 13 04 51" src="https://cloud.githubusercontent.com/assets/23944/13351830/b96a0fde-dc89-11e5-82d6-ec19f7ec0099.png">

I run the tests with `$ meteor test-app --unit --settings=settings-dev.json --driver-package avital:mocha`.

Note that I'm not running tests as a package, but with `test-app`, so I don't have any `packages.js` at all.

Of course I did `$ npm install` and installed as well `avital:mocha` package, but I get undefined when importing mocha. Do you have the same issue? Maybe a bug in 1.3 or in the package?

**Comment by avital** [comment]
The `avital:mocha` package doesn't export a `mocha` object.
